--- #YAML:1.0
FinancialFunctions:
  FinancialFunction:
    - Abbreviation: linear_regression
      CamelCaseName: LinearRegression
      Flags:
        Flag: Overlap
      GroupId: Statistic Functions
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outRegression
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Close
          Type: Close
      ShortDescription: Linear Regression
    - Abbreviation: detrend
      CamelCaseName: Detrend
      Flags:
        Flag: Overlap
      GroupId: Statistic Functions
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outDetrended
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Close
          Type: Close
      ShortDescription: Detrended close
    - Abbreviation: detrended_stddev
      CamelCaseName: DetrendedStddev
      GroupId: Statistic Functions
      OptionalInputArguments:
        OptionalInputArgument:
          - DefaultValue: 5
            Name: Time Period
            Range:
              Maximum: 100000
              Minimum: 2
              SuggestedEnd: 100000
              SuggestedIncrement: 100000
              SuggestedStart: 100000
            ShortDescription: Number of period
            Type: Integer
          - DefaultValue: 1.0
            Name: Deviations
            Range:
              Maximum: 3.000000e+37
              Minimum: -3.000000e+37
              Precision: 2
              SuggestedEnd: 2.000000e+0
              SuggestedIncrement: 2.000000e-1
              SuggestedStart: -2.000000e+0
            ShortDescription: Nb of deviations
            Type: Double
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outStddev
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Close
          Type: Close
      ShortDescription: Standard Deviation
    - Abbreviation: zema
      CamelCaseName: Zema
      Flags:
        Flag:
          - Overlap
      GroupId: Moving Averages
      OptionalInputArguments:
        OptionalInputArgument:
          - DefaultValue: .25
            Name: alpha
            Range:
              Maximum: 1
              Minimum: .01
              SuggestedEnd: 1
              SuggestedIncrement: .01
              SuggestedStart: .25
            ShortDescription: Alpha
            Type: Double
          - DefaultValue: 1.0
            Name: Gain
            Range:
              Maximum: 2
              Minimum: 0
              Precision: 2
              SuggestedEnd: 2.0
              SuggestedIncrement: .01
              SuggestedStart: 0
            ShortDescription: Gain for Momentum
            Type: Double
          - DefaultValue: 3
            Name: Lag
            Range:
              Maximum: 5
              Minimum: 1
              Precision: 2
              SuggestedEnd: 5
              SuggestedIncrement: 1
              SuggestedStart: 1
            ShortDescription: Velocity Estimate
            Type: Integer
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outZema
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Price
          Type: Price
      ShortDescription: Zero Lag Moving Average
