--- #YAML:1.0
FinancialFunctions:
  FinancialFunction:
    - Abbreviation: linreg
      CamelCaseName: LinearRegression
      Flags:
        Flag: Overlap
      GroupId: Statistic Functions
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outLinreg
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Close
          Type: Close
      ShortDescription: Linear Regression
    - Abbreviation: detrend
      CamelCaseName: Detrend
      Flags:
        Flag: Overlap
      GroupId: Statistic Functions
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outDetrended
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Close
          Type: Close
      ShortDescription: Detrended close
    - Abbreviation: detrended_stddev
      CamelCaseName: DetrendedStddev
      GroupId: Statistic Functions
      OptionalInputArguments:
        OptionalInputArgument:
          - DefaultValue: 5
            Name: Time Period
            Range:
              Maximum: 100000
              Minimum: 2
              SuggestedEnd: 100000
              SuggestedIncrement: 100000
              SuggestedStart: 100000
            ShortDescription: Number of period
            Type: Integer
          - DefaultValue: 1.0
            Name: Deviations
            Range:
              Maximum: 3.000000e+37
              Minimum: -3.000000e+37
              Precision: 2
              SuggestedEnd: 2.000000e+0
              SuggestedIncrement: 2.000000e-1
              SuggestedStart: -2.000000e+0
            ShortDescription: Nb of deviations
            Type: Double
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outStddev
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Close
          Type: Close
      ShortDescription: Standard Deviation
    - Abbreviation: zema
      CamelCaseName: Zema
      Flags:
        Flag:
          - Overlap
      GroupId: Moving Averages
      OptionalInputArguments:
        OptionalInputArgument:
          - DefaultValue: .25
            Name: alpha
            Range:
              Maximum: 1
              Minimum: .01
              SuggestedEnd: 1
              SuggestedIncrement: .01
              SuggestedStart: .25
            ShortDescription: Alpha
            Type: Double
          - DefaultValue: 1.0
            Name: Gain
            Range:
              Maximum: 2
              Minimum: 0
              Precision: 2
              SuggestedEnd: 2.0
              SuggestedIncrement: .01
              SuggestedStart: 0
            ShortDescription: Gain for Momentum
            Type: Double
          - DefaultValue: 3
            Name: Lag
            Range:
              Maximum: 5
              Minimum: 1
              Precision: 2
              SuggestedEnd: 5
              SuggestedIncrement: 1
              SuggestedStart: 1
            ShortDescription: Velocity Estimate
            Type: Integer
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outZema
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Price
          Type: Price
      ShortDescription: Zero Lag Moving Average
    - Abbreviation: rvi
      CamelCaseName: Rvi
      Flags:
        Flag:
          - Overlap
      GroupId: Volatility Measure
      OptionalInputArguments:
        OptionalInputArgument:
          - DefaultValue: .2
            Name: alpha
            Range:
              Maximum: 1
              Minimum: .01
              SuggestedEnd: 1
              SuggestedIncrement: .01
              SuggestedStart: .25
            ShortDescription: Alpha
            Type: Double
          - DefaultValue: 5
            Name: Period
            Range:
              Maximum: 2
              Minimum: 10000
              Precision: 2
              SuggestedEnd: 2.0
              SuggestedIncrement: .5
              SuggestedStart: 2
            ShortDescription: Period for Smoothing
            Type: Integer
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outRvi
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Low
          Type: Price
          Name: High
          Type: Price
      ShortDescription: Relative Volatility Index
    - Abbreviation: rvig
      CamelCaseName: RVig
      GroupId: Momentum Indicators
      OptionalInputArguments:
        OptionalInputArgument:
          DefaultValue: 10
          Name: Time Period
          Range:
            Maximum: 50
            Minimum: 2
            SuggestedEnd: 50
            SuggestedIncrement: 1
            SuggestedStart: 5
          ShortDescription: Number of period
          Type: Integer
      OutputArguments:
        OutputArgument:
          - Flags:
              Flag: Dashed Line
            Name: outRvi
            Type: Double Array
          - Flags:
              Flag: Line
            Name: outRviSig
            Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          - Name: High
            Type: Price
          - Name: Low
            Type: Price
          - Name: Open
            Type: Price
          - Name: Close
            Type: Price
      ShortDescription: Relative Vigor
