--- #YAML:1.0
FinancialFunctions:
  FinancialFunction:
    - Abbreviation: extract
      CamelCaseName: extract
      Flags:
        Flag: Overlap
      GroupId: Primitive Functions
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outValue
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Close
          Type: Close
      ShortDescription: Returns one of OHLCV(delta, accum_volume)
    - Abbreviation: calculate
      CamelCaseName: calculate
      Flags:
        Flag: Overlap
      GroupId: Primitive Functions
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outResult
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Close
          Type: Close
      ShortDescription: Vector Calculation
    - Abbreviation: linreg
      CamelCaseName: LinearRegression
      Flags:
        Flag: Overlap
      GroupId: Statistic Functions
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outLinreg
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Close
          Type: Close
      ShortDescription: Linear Regression
    - Abbreviation: lrsigma
      CamelCaseName: LRSigma
      GroupId: Statistic Functions
      OutputArguments:
        OutputArgument:
          - Flags:
              Flag: Dashed Line
            Name: outLrSigma
            Type: Double Array
          - Flags:
              Flag: Line
            Name: outResiduals
            Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Close
          Type: Close
      ShortDescription: Linear Regression Sigma
    - Abbreviation: lr
      CamelCaseName: lr
      GroupId: Statistic Functions
      OutputArguments:
        OutputArgument:
          - Flags:
              Flag: Dashed Line
            Name: outLR
            Type: Double Array
          - Flags:
              Flag: Line
            Name: outChisq
            Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Close
          Type: Close
      ShortDescription: Linear Regression (non-lagged)
    - Abbreviation: nreturn
      CamelCaseName: nReturn
      Flags:
        Flag: Overlap
      GroupId: Momentum Indicators
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outNreturn
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Close
          Type: Close
      ShortDescription: Linear Regression
    - Abbreviation: lrsigma
      CamelCaseName: LRSigma
      GroupId: Statistic Functions
      OutputArguments:
        OutputArgument:
          - Flags:
              Flag: Dashed Line
            Name: outLrSigma
            Type: Double Array
          - Flags:
              Flag: Line
            Name: outResiduals
            Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Close
          Type: Close
      ShortDescription: Linear Regression Sigma
    - Abbreviation: zema
      CamelCaseName: Zema
      Flags:
        Flag:
          - Overlap
      GroupId: Moving Averages
      OptionalInputArguments:
        OptionalInputArgument:
          - DefaultValue: .25
            Name: alpha
            Range:
              Maximum: 1
              Minimum: .01
              SuggestedEnd: 1
              SuggestedIncrement: .01
              SuggestedStart: .25
            ShortDescription: Alpha
            Type: Double
          - DefaultValue: 1.0
            Name: Gain
            Range:
              Maximum: 2
              Minimum: 0
              Precision: 2
              SuggestedEnd: 2.0
              SuggestedIncrement: .01
              SuggestedStart: 0
            ShortDescription: Gain for Momentum
            Type: Double
          - DefaultValue: 3
            Name: Lag
            Range:
              Maximum: 5
              Minimum: 1
              Precision: 2
              SuggestedEnd: 5
              SuggestedIncrement: 1
              SuggestedStart: 1
            ShortDescription: Velocity Estimate
            Type: Integer
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outZema
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Price
          Type: Price
      ShortDescription: Zero Lag Moving Average
    - Abbreviation: rvi
      CamelCaseName: Rvi
      Flags:
        Flag:
          - Overlap
      GroupId: Volatility Measure
      OptionalInputArguments:
        OptionalInputArgument:
          - DefaultValue: 14
            Name: Time Period
            Range:
              Maximum:  1000
              Minimum: 2
              Precision: 2
              SuggestedEnd: 252
              SuggestedIncrement: 1
              SuggestedStart: 5
            ShortDescription: Period for Smoothing
            Type: Integer
      OutputArguments:
        OutputArgument:
          Flags:
            Flag: Line
          Name: outRvi
          Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          Name: Low
          Type: Price
          Name: High
          Type: Price
      ShortDescription: Relative Volatility Index
    - Abbreviation: rvig
      CamelCaseName: RVig
      GroupId: Momentum Indicators
      OptionalInputArguments:
        OptionalInputArgument:
          DefaultValue: 10
          Name: Time Period
          Range:
            Maximum: 50
            Minimum: 2
            SuggestedEnd: 50
            SuggestedIncrement: 1
            SuggestedStart: 5
          ShortDescription: Number of period
          Type: Integer
      OutputArguments:
        OutputArgument:
          - Flags:
              Flag: Dashed Line
            Name: outRvi
            Type: Double Array
          - Flags:
              Flag: Line
            Name: outRviSig
            Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          - Name: High
            Type: Price
          - Name: Low
            Type: Price
          - Name: Open
            Type: Price
          - Name: Close
            Type: Price
      ShortDescription: Relative Vigor
    - Abbreviation: mom_percent
      CamelCaseName: MomPercent
      GroupId: Momentum Indicators
      OptionalInputArguments:
        OptionalInputArgument:
          DefaultValue: 0
          Name: Time Period
          Range:
            Maximum: 50
            Minimum: 0
            SuggestedEnd: 50
            SuggestedIncrement: 1
            SuggestedStart: 0
          ShortDescription: Number of period
          Type: Integer
      OutputArguments:
        OutputArgument:
          - Flags:
              Flag: Dashed Line
            Name: outMomPercent
            Type: Double Array
      RequiredInputArguments:
        RequiredInputArgument:
          - Name: Close
            Type: Price
      ShortDescription: Momentum Percent
